url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jacob Epstein" # the name of your site, e.g. ACME Corp.
description: "Undergraduate studying Computer Science & Math at UMass Amherst"
future: true